#image: registry.docker.local/xuwang/dind
#script:
#  - dkbuild registry.docker.local/xuwang/echo  /var/cache/drone/src/github.com/xuwang/docker-echo
#
## docker service is not fully working today ...
#image: google/golang:1.3.1
image: registry.docker.local/xuwang/dind
publish:
    docker:
        dockerfile: Dockerfile
    #    docker_server: kube-1.docker.local
    #    docker_port: 2375
    #    docker_version: 1.2.0
        registry_host: registry.docker.local
    #    registry_protocol: http
    #    registry_login: false
    #    registry_login_uri: /registry/v1/
    #    username: myuser
    #    password: mypassword
    #    email: myuser@example.com
        image_name: test/echo
        push_latest: true
        keep_builds: true
        custom_tag: 0.1
